apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-11-12T20:36:48Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "13655"
  selfLink: /api/v1/namespaces/default/services/hello-world-rest-api
  uid: 952eef7e-2f2b-41e7-8ec5-56d003811f73
spec:
  clusterIP: 10.4.6.245
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30134
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.224.117.182